"""empty message

Revision ID: a921de5846c7
Revises: 14e9ec1362c7
Create Date: 2019-05-18 14:48:47.612137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a921de5846c7'
down_revision = '14e9ec1362c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('username', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
