"""empty message

Revision ID: c167c8b0b3f2
Revises: 9d3a1c7121e3
Create Date: 2019-05-18 14:33:31.452420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c167c8b0b3f2'
down_revision = '9d3a1c7121e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('phonename', sa.String(length=255), nullable=True))
    op.add_column('vote', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'username')
    op.drop_column('vote', 'phonename')
    # ### end Alembic commands ###
